### ISSUE TITLE
issues using the customSchemas

### ISSUE THREAD

**Issue by ghost** [pethron/gsuite-custom-schema-update#1]
Hi, I keep getting KeyError - can't figure out what exactly is happening. Any ideas
  File "/Users/xxx..gsuite-custom-schema-update/gsuite_update_script/run.py", line 97, in main
    userUpdated = update_saml_attributes(service, user, schema_config, federation['federations'])
  File "/Users/xxxx/ gsuite-custom-schema-update/gsuite_update_script/run.py", line 54, in update_saml_attributes
    current_schemas = user['customSchemas']
KeyError: 'customSchemas'

**Comment by pethron** [comment]
The error is due to not finding the correct key in the user.

The user has already some custom schema assigned?
Did you select a multi-value field for the federated role field?

**Comment by ghost** [comment]
The user has already some custom schema assigned? - correct we have few other apps, that's using custom-attributes, but we are trying to see if we can use the AWS SAML custom attribute to populate automatically.
Did you select a multi-value field for the federated role field? - Yes it's setup as multi-value

**Comment by pethron** [comment]
Do you mind putting a print before line 54 and see what actually is the content of the user? Check if 'customSchemas' key is present

**Comment by ghost** [comment]
Hi

So i ran the debugger for a test user, and this is all the information I
can see.. It doesn't show the custom attributes

{'kind': 'admin#directory#user', 'id': '10070304X’XXXXXXXXX, 'etag':
'"Az0XXXXXXXXXXXM5vU/DXXXX07gE"', 'primaryEmail': ‘XYZ@XYZ.com', 'name':
{'givenName': 'iXXXX', 'familyName': 'XXXijXXXX', 'fullName': 'XXXXXXX'},
'isAdmin': False, 'isDelegatedAdmin': False, 'lastLoginTime':
'1970-01-01T00:00:00.000Z', 'creationTime': '2021-03-23T20:41:21.000Z',
'agreedToTerms': False, 'suspended': False, 'archived': False,
'changePasswordAtNextLogin': True, 'ipWhitelisted': False, 'emails':
[{'address': 'iEEEEEE@EEEEEEE.com', 'primary': True}], 'customerId':
‘XXXXXXXXX’, 'orgUnitPath': '/AWS', 'isMailboxSetup': False,
'isEnrolledIn2Sv': False, 'isEnforcedIn2Sv': True,
'includeInGlobalAddressList': True}

This is from gsuite
[image: image.png]
[image: image.png]
[image: image.png]

Kind Regards

**Comment by pethron** [comment]
I think the reason could be you don't have permission. Have you enabled the admin-sdk and do a check it?

**Comment by ghost** [comment]
The user is a super admin and had the admin SDK enabled to the scopes.
i started the whole thing from scratch, recreated the whole project, and
used the API explore, and noticed I couldn't see the customSchemas- and you
were right, It could have been a permissions issue.
Thanks for publishing the script, it will definitely save our IT team and
whole amount of time.
<https://www.googleapis.com/auth/admin.directory.user>

kind regards

**Comment by pethron** [comment]
Happy you found this useful! If you'd like to stay in touch and get more info about projects related to this come to the Leapp repository:

https://github.com/Noovolari/leapp

**Comment by ghost** [comment]
Hi Pethron

I had one question that I couldn't ask the other day. Basically if the AWS
saml custom attribute is empty and nothing on the user  I still KeyError:
'customSchemas'
However if i add something and then try to update, it works.

Are you aware why that happens btw?

Kind regards

**Comment by pethron** [comment]
Hi! Yeah, I'm aware it happens. I didn't put any validation in the code (but still happens when calling the update API, so you see an error from google) so the script assumes that each element in the configuration file is filled.
